project_id = "wyrieetebfzmgffxecpz"

[functions.trigger-automated-message]
verify_jwt = false

[functions.admin-change-company-subscription]
verify_jwt = false

[functions.check-opportunity-tracking]
verify_jwt = false

[functions.admin-bulk-update-academy-students]
verify_jwt = false
